{% set name = "jupyterlab_code_formatter" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/ryantam626/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5e721119c77d88d8215a8ef401dbc56b90ccc4cd10f269b5d37d501ebf94293b

build:
  number: 0
  noarch: python

requirements:
  build:
    - nodejs
  host:
    - jupyterlab >=1
    - pip
    - python >=3.6
  run:
    - jupyterlab >=1
    - nodejs
    - packaging
    - python >=3.6

test:
  imports:
    - jupyterlab_code_formatter

about:
  home: https://github.com/ryantam626/jupyterlab_code_formatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A universal code formatter for JupyterLab.

extra:
  recipe-maintainers:
    - dbast
    - xhochy
