{% set name = "jupyterlab_code_formatter" %}
{% set version = "0.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/ryantam626/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a9b0c3ad97a991603385af2676e20668b7d6d812bd744f0cdf1de4bcdff4ff9f

build:
  number: 0
  noarch: python

requirements:
  build:
    - nodejs
  host:
    - jupyterlab >=1
    - pip
    - python >=3.6
  run:
    - jupyterlab >=1
    - nodejs
    - python >=3.6

test:
  imports:
    - jupyterlab_code_formatter

about:
  home: https://github.com/ryantam626/jupyterlab_code_formatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A universal code formatter for JupyterLab.

extra:
  recipe-maintainers:
    - dbast
    - xhochy
