{% set name = "jupyterlab_code_formatter" %}
{% set version = "0.5.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/ryantam626/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d8a1dc1c2a4ff376a0161160428d9be166d11a11cf6a3abd0efb79ff7796f71a

build:
  number: 0
  noarch: python

requirements:
  build:
    - nodejs
  host:
    - jupyterlab >=1
    - pip
    - python >=3.6
  run:
    - jupyterlab >=1
    - nodejs
    - python >=3.6

test:
  imports:
    - jupyterlab_code_formatter

about:
  home: https://github.com/ryantam626/jupyterlab_code_formatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A universal code formatter for JupyterLab.

extra:
  recipe-maintainers:
    - dbast
    - xhochy
