{% set name = "jupyterlab_code_formatter" %}
{% set version = "1.4.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b05f65b4b1499feeccae0d273b8fad8d37f6c8acaa32da10d4fc00dc223d2bde

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --install-option="--skip-npm" -vv

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.6
  run:
    - jupyterlab >=3
    - python >=3.6

test:
  imports:
    - jupyterlab_code_formatter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ryantam626/jupyterlab_code_formatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A universal code formatter for JupyterLab.

extra:
  recipe-maintainers:
    - dbast
    - xhochy
