{% set name = "jupyterlab_code_formatter" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fee065a8818a81fab8fa155f238be5e56fb4ac6b05f7df8becfea5a79de9e7a5

build:
  number: 0
  noarch: python

requirements:
  host:
    - jupyter-packaging
    - pip
    - poetry
    - python >=3.6
  run:
    - jupyterlab >=1
    - nodejs
    - packaging
    - python >=3.6

test:
  imports:
    - jupyterlab_code_formatter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ryantam626/jupyterlab_code_formatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A universal code formatter for JupyterLab.

extra:
  recipe-maintainers:
    - dbast
    - xhochy
