{% set name = "jupyterlab_code_formatter" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 029be0f1e29989eba0363fc661e8aa9225495284d2fbff771631089a7936c836

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - jupyterlab >=1
    - nodejs
    - packaging
    - python >=3.6

test:
  imports:
    - jupyterlab_code_formatter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ryantam626/jupyterlab_code_formatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A universal code formatter for JupyterLab.

extra:
  recipe-maintainers:
    - dbast
    - xhochy
