{% set name = "jupyterlab_code_formatter" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8065aa00f2e67ace8fa9d28b62ad4d3e8c36dee2f74e53a0d122a41ead22c5ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=1.4.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
    - python >=3.7
    - pip
  run:
    - jupyter_server >=1.21,<3
    - python >=3.7

test:
  imports:
    - jupyterlab_code_formatter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ryantam626/jupyterlab_code_formatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A universal code formatter for JupyterLab.

extra:
  recipe-maintainers:
    - dbast
    - xhochy
