{% set name = "jupyterlab_code_formatter" %}
{% set version = "3.1.0" %}
{% set tests_to_skip = "test_can_use_styler" %}
{% set tests_to_skip = tests_to_skip + " or test_env_pollution_on_import" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d28a0f7e1a7013f35e1c7f47c09e21f56a2947e5760a5abbb792696fdb27023

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
  run:
    - jupyter_server >=2.4.0,<3
    - packaging
    - python
  run_constrained:
    - notebook >=6,<8

test:
  source_files:
    - jupyterlab_code_formatter/tests
  imports:
    - jupyterlab_code_formatter
  requires:
    - jupyterlab
    - pip
    - pytest
    - pytest-asyncio
    - pytest-jupyter >=0.6.0
    - pytest-jupyter-server >=0.6.0
    - black >=22.1.0,<24  # [py<313]
    - isort
    - yapf
    # - rpy2 # missing
    - importlib_metadata  # [py<38]
    - ruff
    - jupyterlab >=4,<5
  commands:
    - pip check
    - jupyter server extension list
    - jupyter server extension list 2>&1 | grep -ie "jupyterlab_code_formatter.*OK"  # [not win]
    - jupyter server extension list 2>&1 | findstr /i /r "jupyterlab_code_formatter.*OK"  # [win]
    - jupyter labextension list
    # extension is marked as enbaled and outdated, contrary to what the changelog states, but is still functional
    #- jupyter labextension list 2>&1 | grep -ie "jupyterlab_code_formatter.*OK.*(python, jupyterlab-code-formatter)"
    # missing styler for test_can_use_styler*
    # some issues with subprocess call inside test on windows
    - pytest -p pytest_jupyter.jupyter_server -vv jupyterlab_code_formatter/tests -k "not ({{ tests_to_skip }})"  # [py<313]

about:
  home: https://github.com/ryantam626/jupyterlab_code_formatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A JupyterLab plugin to facilitate invocation of code formatters.
  dev_url: https://github.com/ryantam626/jupyterlab_code_formatter
  doc_url: https://jupyterlab-code-formatter.readthedocs.io/
  description: A JupyterLab plugin to facilitate invocation of code formatters.

extra:
  recipe-maintainers:
    - dbast
    - xhochy
